// Generated by packages/find_versions.py. Do not edit.
export const versions = {
  "anyio": {
    "name": "anyio",
    "version": "3.4.0",
    "source": "pypi"
  },
  "idna": {
    "name": "idna",
    "version": "3.3",
    "source": "pypi"
  },
  "sniffio": {
    "name": "sniffio",
    "version": "1.2.0",
    "source": "pypi"
  },
  "starlette": {
    "name": "starlette",
    "version": "0.17.1",
    "source": "pypi"
  },
  "htmltools": {
    "name": "htmltools",
    "version": "0.1.0.9000",
    "source": "local"
  },
  "shiny": {
    "name": "shiny",
    "version": "0.2.0.9002",
    "source": "local"
  }
}